source("RunScript.R")

run_script("Describe_Participants")
run_script("Describe_Data")
run_script("Acceptance")
run_script("ANCOVA")
run_script("Confirmation_analysis")
run_script("PowerAnalysis")
run_script("Exploration")
run_script("Validity_Checks")
run_script("Attari-12")
